### ISSUE TITLE
Generating binary files on Windows

### ISSUE THREAD

**Issue by palazzol** [AK6DN/obj2bin#1]
I am running this script on windows, and I found that under some circumstances, extra line feeds were being inserted into BINA files.  I'm not a perl expert, but it looks like, to support windows, binary files need to be opened slightly differently.

To fix it, I added the line:
```
binmode $OBJ;
```
in two places - the first line after:
```
if ($romtype eq 'BOOT' || $romtype eq 'DIAG') {
```
and also after:
```
} elsif ($romtype eq 'BINA') {
```
I assume for ASC9 files, the line endings don't matter?
If these changes don't hurt on Linux, it's probably a good fix.  
I can submit a Pull Request if you like.

Thanks BTW for the handy tool!

**Comment by AK6DN** [comment]
Thanks for the report. I've used this perl script only within the cygwin environment on windows (with it's perl port) and not using a native windows version of perl. Have never run across this issue. That being said, you are correct in noticing that for some of the input and output files that are being read/written in binary mode, I should have used the binmode() call on the file handle to disable any funky ASCII character processing.

I don't think your changes are quite right, however. After some inspection, I added two calls, but differently:

```
diff --git a/obj2bin.pl b/obj2bin.pl
index ca395ba..56f5bfb 100644
--- a/obj2bin.pl
+++ b/obj2bin.pl
@@ -401,6 +401,7 @@ foreach my $pass (1..2) {
        my $OBJ = FileHandle->new("< ".$objfile);
        die "Error: can't open input object file '$objfile'\n" unless defined $OBJ;
        printf $LOG "\n\nPROCESS PASS %d FILE %d '%s'\n\n", $pass, $numb+1, $objfile if $DEBUG;
+       binmode($OBJ);
        while (my @rec = &read_rec($OBJ)) { &parse_rec($numb+1, $pass, \@rec); }
        $OBJ->close;
     }
@@ -502,6 +503,8 @@ if ($romtype eq 'BOOT' || $romtype eq 'DIAG') {
     # there is no checksum.  If the origin is not 000001, then the origin is
     # the PC at which to start the program.

+    binmode($OUT);
+
     $bytesper = 128 if $bytesper <= 0;
```

The first for the input object files, which are strict binary data files.
And the second for the specific case of a binary output file.
The other output files are all ASCII text files (listings, dump file, intel hex file, etc).

I have rerun all my macro11 compiles / links using this tool, and all the generated binary files are ok.
So for my cygwin usage, the binmode() calls made no difference.

I have checked in a new commit with these two changes, and if you can then test the update version to see if your problem goes away. 

Then one more commit to bump the version to v2.2 and add a change note.

Don

**Comment by palazzol** [comment]
That fix works just fine for me too - I tried it out here.
Thanks for the corrections!

FWIW - I am using a native Windows build of macro11, and then postprocessing with obj2bin.pl using Strawberry Perl for Windows.  I'm probably the only one doing it this way, so I'm glad I could contribute :)

-Frank

**Comment by AK6DN** [comment]
Indeed, most other users I am aware of are on linux or cygwin on windows. Good to hear it fixed the issue. It was an oversight on my part long ago to not add the binmode() call on binary files just in case. I did one more commit to just bump the version number. Closing this out.
